// <auto-generated />
using System;
using MCAROC_Analysis.Data;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCAROC_Analysis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919090000_AddClientScopedAutoFetchDuplicateKey")]
    partial class AddClientScopedAutoFetchDuplicateKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.McaRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<string>("AutoFetchCompanyIdentifier")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasIndex("ClientId", "AutoFetchCompanyIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UX_McaRequests_Client_AutoFetchIdentifier")
                        .HasFilter("[AutoFetchCompanyIdentifier] IS NOT NULL");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.ToTable("Requests");
                });

#pragma warning restore 612, 618
        }
    }
}
