// <auto-generated />
using System;
using MCAROC_Analysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCAROC_Analysis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.AuditorObservation", b =>
                {
                    b.Property<long>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ObservationId"));

                    b.Property<string>("AuditorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<bool>("HasQualificationOrAdverseRemark")
                        .HasColumnType("bit");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("ObservationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObservationId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("AuditorObservations");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientId"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1L,
                            ClientCode = "HDFC",
                            ClientName = "HDFC Bank",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            ClientId = 2L,
                            ClientCode = "KOTAK",
                            ClientName = "Kotak Mahindra Bank",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            ClientId = 3L,
                            ClientCode = "AUSFB",
                            ClientName = "AU Small Finance Bank",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            ClientId = 4L,
                            ClientCode = "FEDERAL",
                            ClientName = "Federal Bank",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.CompanyProfile", b =>
                {
                    b.Property<long>("CompanyProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CompanyProfileId"));

                    b.Property<decimal?>("AuthorisedCapital")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BusinessActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("IncorporationDate")
                        .HasColumnType("date");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Llpin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaidUpCapital")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyProfileId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.Director", b =>
                {
                    b.Property<long>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DirectorId"));

                    b.Property<DateOnly?>("CessationDate")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DesignationAppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("Din")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OriginalAppointmentDate")
                        .HasColumnType("date");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.DirectorAssociation", b =>
                {
                    b.Property<long>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssociationId"));

                    b.Property<string>("ActiveCompliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CessationDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedCin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedCompanyNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectedCompanyRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorporateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfIncorporation")
                        .HasColumnType("date");

                    b.Property<string>("DirectorDin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorNameRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PaidUpCapitalCrore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SumOfChargesCrore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("AssociationId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("DirectorAssociations");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.EpfoContribution", b =>
                {
                    b.Property<long>("EpfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EpfoId"));

                    b.Property<decimal?>("ContributionAmountCrore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("EstablishmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WageMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EpfoId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("EpfoContributions");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.FinancialYearData", b =>
                {
                    b.Property<long>("FinancialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FinancialId"));

                    b.Property<decimal?>("CashAndBank")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cff")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cfi")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cfo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentAssets")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentLiabilities")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Ebit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Ebitda")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FinanceCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Inventory")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("LongTermBorrowings")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NetWorth")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OtherIncome")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pat")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pbt")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Revenue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ShareCapital")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ShortTermBorrowings")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalDebt")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TradePayables")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TradeReceivables")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("FinancialId");

                    b.HasIndex("RequestId", "IngestionRunId", "FinancialYear");

                    b.ToTable("FinancialYearData");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.GstFiling", b =>
                {
                    b.Property<long>("GstFilingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GstFilingId"));

                    b.Property<int?>("DelayDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("FilingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GstRegistrationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GstFilingId");

                    b.HasIndex("GstRegistrationId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("GstFilings");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.GstRegistration", b =>
                {
                    b.Property<long>("GstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GstId"));

                    b.Property<DateOnly?>("CancellationDate")
                        .HasColumnType("date");

                    b.Property<string>("Flags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("NatureOfBusinessActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxpayerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GstId");

                    b.HasIndex("RequestId", "IngestionRunId", "Gstin");

                    b.ToTable("GstRegistrations");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.IngestionIssue", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IssueId"));

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SheetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IssueId");

                    b.HasIndex("IngestionRunId");

                    b.ToTable("IngestionIssues");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.IngestionRun", b =>
                {
                    b.Property<long>("IngestionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngestionRunId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("RowsExtracted")
                        .HasColumnType("int");

                    b.Property<int>("RunNumber")
                        .HasColumnType("int");

                    b.Property<long?>("SourceChargeDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceRocDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("WarningsCount")
                        .HasColumnType("int");

                    b.HasKey("IngestionRunId");

                    b.HasIndex("RequestId", "RunNumber")
                        .IsUnique();

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.Litigation", b =>
                {
                    b.Property<long>("LitigationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LitigationId"));

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Court")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("LastHearingDate")
                        .HasColumnType("date");

                    b.Property<string>("Litigants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LitigationId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("Litigations");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.McaRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime?>("AnalysisCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AnalysisStartedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasIngestionWarnings")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManualReviewRequired")
                        .HasColumnType("bit");

                    b.Property<long?>("LatestCompletedIngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Llpin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.MsmePayment", b =>
                {
                    b.Property<long>("MsmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MsmeId"));

                    b.Property<decimal?>("AmountDueCrore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportingPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierNameRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierPan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MsmeId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("MsmePayments");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.RequestDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuarantineReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDocuments");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.RocCharge", b =>
                {
                    b.Property<long>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChargeId"));

                    b.Property<string>("ChargeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreationDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CurrentAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CurrentAmountRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("LatestChargeHolderNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestChargeHolderRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("LatestModificationDate")
                        .HasColumnType("date");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("RocChargeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("SatisfactionDate")
                        .HasColumnType("date");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChargeId");

                    b.HasIndex("RequestId", "IngestionRunId", "RocChargeNumber");

                    b.ToTable("RocCharges");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.RocChargeEvent", b =>
                {
                    b.Property<long>("ChargeEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChargeEventId"));

                    b.Property<decimal?>("ChargeAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ChargeAmountRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ConsortiumHolding")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExtentAndOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("HolderNameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolderNameRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("InstrumentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("JointHolding")
                        .HasColumnType("bit");

                    b.Property<string>("MatchConfidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatchMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificationParticulars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfHolders")
                        .HasColumnType("int");

                    b.Property<string>("OtherTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyParticulars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RateOfInterest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("RocChargeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfPayment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChargeEventId");

                    b.HasIndex("RocChargeId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("RocChargeEvents");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.Shareholding", b =>
                {
                    b.Property<long>("ShareholdingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShareholdingId"));

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("HoldingPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPromoter")
                        .HasColumnType("bit");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShareholderNameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareholderNameRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareholderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SharesHeld")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceSheetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ShareholdingId");

                    b.HasIndex("RequestId", "IngestionRunId");

                    b.ToTable("Shareholdings");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.GstFiling", b =>
                {
                    b.HasOne("MCAROC_Analysis.Data.Entities.GstRegistration", null)
                        .WithMany("Filings")
                        .HasForeignKey("GstRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.IngestionIssue", b =>
                {
                    b.HasOne("MCAROC_Analysis.Data.Entities.IngestionRun", "IngestionRun")
                        .WithMany("Issues")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.IngestionRun", b =>
                {
                    b.HasOne("MCAROC_Analysis.Data.Entities.McaRequest", "Request")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.McaRequest", b =>
                {
                    b.HasOne("MCAROC_Analysis.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.RequestDocument", b =>
                {
                    b.HasOne("MCAROC_Analysis.Data.Entities.McaRequest", "Request")
                        .WithMany("Documents")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.RocChargeEvent", b =>
                {
                    b.HasOne("MCAROC_Analysis.Data.Entities.RocCharge", "RocCharge")
                        .WithMany("Events")
                        .HasForeignKey("RocChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RocCharge");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.GstRegistration", b =>
                {
                    b.Navigation("Filings");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.IngestionRun", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.McaRequest", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("IngestionRuns");
                });

            modelBuilder.Entity("MCAROC_Analysis.Data.Entities.RocCharge", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
