<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e2216c72-57cf-4cd5-b4a6-b4ef959959f1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.9.0" />
    <PackageReference Include="Google.GenAI" Version="1.21.0" />
    <PackageReference Include="Microsoft.Build.Tasks.Git" Version="10.0.401">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <PackageReference Include="PDFtoImage" Version="5.4.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="ReportTemplates\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
